# Generated by Django 4.2.7 on 2025-05-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_produtos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='numero',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
